version: '3'
services:
  web:
    container_name: mantastyle-telco-customer-churn-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: npm run dev